# Generated by Django 4.0.4 on 2022-04-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_company', models.CharField(max_length=20)),
                ('current_company', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('job_post', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('highest_degree', models.CharField(max_length=10)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=10)),
                ('experience_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.experiencedetails')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('job_post', models.CharField(max_length=20)),
                ('job_location', models.CharField(max_length=20)),
                ('job_description', models.CharField(max_length=20)),
                ('company_url', models.CharField(max_length=20)),
                ('job_skill_set', models.ManyToManyField(blank=True, null=True, to='main.jobskillset')),
            ],
        ),
    ]
