# Generated by Django 4.0.4 on 2022-04-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_register_city_register_first_name_register_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='city',
        ),
        migrations.RemoveField(
            model_name='register',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
    ]
