# Generated by Django 4.0.4 on 2022-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profileform_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='is_fresher',
            field=models.BooleanField(default=False),
        ),
    ]
