# Generated by Django 4.0.4 on 2022-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profileform_is_fresher'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
