# Generated by Django 4.0.4 on 2022-04-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_companydetails_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileform',
            name='jobs_applied',
            field=models.ManyToManyField(blank=True, null=True, to='main.companydetails'),
        ),
    ]
