# Generated by Django 4.0.4 on 2022-04-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profileform_jobs_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='is_applied',
        ),
    ]
