# Generated by Django 4.0.4 on 2022-05-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_companydetails_is_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='job_description',
            field=models.CharField(max_length=1024),
        ),
    ]
